"""empty message

Revision ID: 43608765f053
Revises: a199bef7b254
Create Date: 2023-04-23 16:02:15.413233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43608765f053'
down_revision = 'a199bef7b254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_project', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('owner_project')

    # ### end Alembic commands ###
