"""empty message

Revision ID: 725ddc0ea264
Revises: 9f055d12e3e5
Create Date: 2023-04-18 22:19:58.968078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725ddc0ea264'
down_revision = '9f055d12e3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipaddr', sa.String(length=20), nullable=False),
    sa.Column('ssh_user', sa.String(length=64), nullable=False),
    sa.Column('ssh_passwd', sa.String(length=64), nullable=False),
    sa.Column('encoding', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('activate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host')
    # ### end Alembic commands ###
