"""empty message

Revision ID: 9a58b31ec140
Revises: 43608765f053
Create Date: 2023-04-23 19:44:24.517536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a58b31ec140'
down_revision = '43608765f053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_host', sa.Integer(), nullable=False))
        batch_op.drop_column('owner_project')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_project', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('owner_host')

    # ### end Alembic commands ###
