"""empty message

Revision ID: e712be82b941
Revises: c26b6ea7271d
Create Date: 2023-04-22 01:57:33.577264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e712be82b941'
down_revision = 'c26b6ea7271d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('child_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
